#Compressed Blocks configuration
#Changes require a game restart to take effect.
#WARNING: These settings are loaded on startup and not synced with the server.
#Ensure identical configuration on both client and server to prevent connection issues.
#Any changes will log warnings for invalid or missing files.
#----------------------------------------
#Enable compressed blocks
blocksEnabled = true
#Enable crates
cratesEnabled = false
#Maximum compression level for blocks
# Default: 10
# Range: 1 ~ 10
maxCompressionLevel = 9
#Maximum compression level for crates
# Default: 10
# Range: 1 ~ 10
maxCrateCompressionLevel = 1
#Enabled blocks:
DIRT = false
GRAVEL = false
COBBLESTONE = false
#Note: Stone can not be disabled as it is required for the creative inventory icon.
STONE = true
GRANITE = false
DIORITE = false
ANDESITE = false
CRIMSON_NYLIUM = false
WARPED_NYLIUM = false
CLAY = false
SAND = false
RED_SAND = false
SANDSTONE = false
RED_SANDSTONE = false
COAL_ORE = false
COPPER_ORE = false
IRON_ORE = false
GOLD_ORE = false
REDSTONE_ORE = false
EMERALD_ORE = false
LAPIS_ORE = false
DIAMOND_ORE = false
NETHER_GOLD_ORE = false
NETHER_QUARTZ_ORE = false
DEEPSLATE_COAL_ORE = true
DEEPSLATE_COPPER_ORE = true
DEEPSLATE_IRON_ORE = true
DEEPSLATE_GOLD_ORE = true
DEEPSLATE_REDSTONE_ORE = true
DEEPSLATE_EMERALD_ORE = true
DEEPSLATE_LAPIS_ORE = true
DEEPSLATE_DIAMOND_ORE = true
RAW_IRON_BLOCK = false
RAW_COPPER_BLOCK = false
RAW_GOLD_BLOCK = false
IRON_BLOCK = false
GOLD_BLOCK = false
REDSTONE_BLOCK = false
EMERALD_BLOCK = false
LAPIS_BLOCK = false
DIAMOND_BLOCK = false
NETHERITE_BLOCK = false
COAL_BLOCK = false
SLIME_BLOCK = false
HONEY_BLOCK = false
BRICKS = false
STONE_BRICKS = false
NETHERRACK = false
NETHER_BRICKS = false
RED_NETHER_BRICKS = false
NETHER_WART_BLOCK = false
SOUL_SAND = false
SOUL_SOIL = false
END_STONE = false
END_STONE_BRICKS = false
BLACKSTONE = false
DEEPSLATE = false
COBBLED_DEEPSLATE = false
TUFF = false
BASALT = false
OBSIDIAN = false
MUD = false
OAK_LOG = false
SPRUCE_LOG = false
BIRCH_LOG = false
JUNGLE_LOG = false
ACACIA_LOG = false
DARK_OAK_LOG = false
MANGROVE_LOG = false
CHERRY_LOG = false
STRIPPED_OAK_LOG = false
STRIPPED_SPRUCE_LOG = false
STRIPPED_BIRCH_LOG = false
STRIPPED_JUNGLE_LOG = false
STRIPPED_ACACIA_LOG = false
STRIPPED_DARK_OAK_LOG = false
STRIPPED_MANGROVE_LOG = false
STRIPPED_CHERRY_LOG = false
OAK_PLANKS = false
SPRUCE_PLANKS = false
BIRCH_PLANKS = false
JUNGLE_PLANKS = false
ACACIA_PLANKS = false
DARK_OAK_PLANKS = false
MANGROVE_PLANKS = false
CHERRY_PLANKS = false
BAMBOO_PLANKS = false
BAMBOO_MOSAIC = false
COPPER_BLOCK = false
CUT_COPPER = false
EXPOSED_COPPER = false
EXPOSED_CUT_COPPER = false
WEATHERED_COPPER = false
WEATHERED_CUT_COPPER = false
OXIDIZED_COPPER = false
OXIDIZED_CUT_COPPER = false
WAXED_COPPER_BLOCK = false
WAXED_CUT_COPPER = false
WAXED_EXPOSED_COPPER = false
WAXED_EXPOSED_CUT_COPPER = false
WAXED_WEATHERED_COPPER = false
WAXED_WEATHERED_CUT_COPPER = false
WAXED_OXIDIZED_COPPER = false
WAXED_OXIDIZED_CUT_COPPER = false
BONE_BLOCK = false
SCULK = false
SMOOTH_SANDSTONE = false
CUT_SANDSTONE = false
CHISELED_SANDSTONE = false
SMOOTH_RED_SANDSTONE = false
CUT_RED_SANDSTONE = false
CHISELED_RED_SANDSTONE = false
CRIMSON_STEM = false
WARPED_STEM = false
TNT = false
BAMBOO_BLOCK = false
STRIPPED_BAMBOO_BLOCK = false
STRIPPED_CRIMSON_STEM = false
CRIMSON_PLANKS = false
STRIPPED_WARPED_STEM = false
WARPED_PLANKS = false
MOSSY_COBBLESTONE = false
MOSSY_STONE_BRICKS = false
CRACKED_STONE_BRICKS = false
CHISELED_STONE_BRICKS = false
POLISHED_GRANITE = false
POLISHED_DIORITE = false
POLISHED_ANDESITE = false
CHISELED_DEEPSLATE = false
POLISHED_DEEPSLATE = false
DEEPSLATE_BRICKS = false
CRACKED_DEEPSLATE_BRICKS = false
DEEPSLATE_TILES = false
CRACKED_DEEPSLATE_TILES = false
PACKED_MUD = false
MUD_BRICKS = false
PRISMARINE = false
PRISMARINE_BRICKS = false
DARK_PRISMARINE = false
QUARTZ_BLOCK = false
CHISELED_QUARTZ_BLOCK = false
QUARTZ_BRICKS = false
QUARTZ_PILLAR = false
SMOOTH_QUARTZ_BLOCK = false
AMETHYST_BLOCK = false
WHITE_WOOL = false
LIGHT_GRAY_WOOL = false
GRAY_WOOL = false
BLACK_WOOL = false
BROWN_WOOL = false
RED_WOOL = false
ORANGE_WOOL = false
YELLOW_WOOL = false
LIME_WOOL = false
GREEN_WOOL = false
CYAN_WOOL = false
LIGHT_BLUE_WOOL = false
BLUE_WOOL = false
PURPLE_WOOL = false
MAGENTA_WOOL = false
PINK_WOOL = false
TERRACOTTA = false
WHITE_TERRACOTTA = false
LIGHT_GRAY_TERRACOTTA = false
GRAY_TERRACOTTA = false
BLACK_TERRACOTTA = false
BROWN_TERRACOTTA = false
RED_TERRACOTTA = false
ORANGE_TERRACOTTA = false
YELLOW_TERRACOTTA = false
LIME_TERRACOTTA = false
GREEN_TERRACOTTA = false
CYAN_TERRACOTTA = false
LIGHT_BLUE_TERRACOTTA = false
BLUE_TERRACOTTA = false
PURPLE_TERRACOTTA = false
MAGENTA_TERRACOTTA = false
PINK_TERRACOTTA = false
WHITE_GLAZED_TERRACOTTA = false
LIGHT_GRAY_GLAZED_TERRACOTTA = false
GRAY_GLAZED_TERRACOTTA = false
BLACK_GLAZED_TERRACOTTA = false
BROWN_GLAZED_TERRACOTTA = false
RED_GLAZED_TERRACOTTA = false
ORANGE_GLAZED_TERRACOTTA = false
YELLOW_GLAZED_TERRACOTTA = false
LIME_GLAZED_TERRACOTTA = false
GREEN_GLAZED_TERRACOTTA = false
CYAN_GLAZED_TERRACOTTA = false
LIGHT_BLUE_GLAZED_TERRACOTTA = false
BLUE_GLAZED_TERRACOTTA = false
PURPLE_GLAZED_TERRACOTTA = false
MAGENTA_GLAZED_TERRACOTTA = false
PINK_GLAZED_TERRACOTTA = false
WHITE_CONCRETE_POWDER = false
LIGHT_GRAY_CONCRETE_POWDER = false
GRAY_CONCRETE_POWDER = false
BLACK_CONCRETE_POWDER = false
BROWN_CONCRETE_POWDER = false
RED_CONCRETE_POWDER = false
ORANGE_CONCRETE_POWDER = false
YELLOW_CONCRETE_POWDER = false
LIME_CONCRETE_POWDER = false
GREEN_CONCRETE_POWDER = false
CYAN_CONCRETE_POWDER = false
LIGHT_BLUE_CONCRETE_POWDER = false
BLUE_CONCRETE_POWDER = false
PURPLE_CONCRETE_POWDER = false
MAGENTA_CONCRETE_POWDER = false
PINK_CONCRETE_POWDER = false
WHITE_CONCRETE = false
LIGHT_GRAY_CONCRETE = false
GRAY_CONCRETE = false
BLACK_CONCRETE = false
BROWN_CONCRETE = false
RED_CONCRETE = false
ORANGE_CONCRETE = false
YELLOW_CONCRETE = false
LIME_CONCRETE = false
GREEN_CONCRETE = false
CYAN_CONCRETE = false
LIGHT_BLUE_CONCRETE = false
BLUE_CONCRETE = false
PURPLE_CONCRETE = false
MAGENTA_CONCRETE = false
PINK_CONCRETE = false
GLASS = false
TINTED_GLASS = false
WHITE_STAINED_GLASS = false
LIGHT_GRAY_STAINED_GLASS = false
GRAY_STAINED_GLASS = false
BLACK_STAINED_GLASS = false
BROWN_STAINED_GLASS = false
RED_STAINED_GLASS = false
ORANGE_STAINED_GLASS = false
YELLOW_STAINED_GLASS = false
LIME_STAINED_GLASS = false
GREEN_STAINED_GLASS = false
CYAN_STAINED_GLASS = false
LIGHT_BLUE_STAINED_GLASS = false
BLUE_STAINED_GLASS = false
PURPLE_STAINED_GLASS = false
MAGENTA_STAINED_GLASS = false
PINK_STAINED_GLASS = false
ICE = false
PACKED_ICE = false
BLUE_ICE = false
SNOW_BLOCK = false
MOSS_BLOCK = false
CALCITE = false
DRIPSTONE_BLOCK = false
MAGMA_BLOCK = false
GLOWSTONE = false
DRIED_KELP_BLOCK = false
BROWN_MUSHROOM_BLOCK = false
RED_MUSHROOM_BLOCK = false
SHROOMLIGHT = false
MELON = false
PUMPKIN = false
HAY_BLOCK = false
OCHRE_FROGLIGHT = false
VERDANT_FROGLIGHT = false
PEARLESCENT_FROGLIGHT = false
SEA_LANTERN = false
#Enabled crates:
#Note: Apple can not be disabled as it is required for the creative inventory icon.
APPLE = true
GOLDEN_APPLE = false
SWEET_BERRIES = false
GLOW_BERRIES = false
CHORUS_FRUIT = false
CARROT = false
GOLDEN_CARROT = false
POTATO = false
BAKED_POTATO = false
POISONOUS_POTATO = false
BEETROOT = false
BEEF = false
COOKED_BEEF = false
PORKCHOP = false
COOKED_PORKCHOP = false
MUTTON = false
COOKED_MUTTON = false
CHICKEN = false
COOKED_CHICKEN = false
RABBIT = false
COOKED_RABBIT = false
COD = false
COOKED_COD = false
SALMON = false
COOKED_SALMON = false
TROPICAL_FISH = false
PUFFERFISH = false
BREAD = false
COOKIE = false
ROTTEN_FLESH = false
SPIDER_EYE = false
HONEY_BOTTLE = false
CHARCOAL = false
QUARTZ = false
AMETHYST_SHARD = false
STICK = false
FLINT = false
BONE = false
STRING = false
FEATHER = false
SNOWBALL = false
EGG = false
LEATHER = false
RABBIT_HIDE = false
HONEYCOMB = false
INK_SAC = false
GLOW_INK_SAC = false
TURTLE_SCUTE = false
CLAY_BALL = false
NAUTILUS_SHELL = false
FIRE_CHARGE = false
BLAZE_ROD = false
NETHER_STAR = false
ENDER_PEARL = false
ENDER_EYE = false
SHULKER_SHELL = false
WHITE_DYE = false
LIGHT_GRAY_DYE = false
GRAY_DYE = false
BLACK_DYE = false
BROWN_DYE = false
RED_DYE = false
ORANGE_DYE = false
YELLOW_DYE = false
LIME_DYE = false
GREEN_DYE = false
CYAN_DYE = false
LIGHT_BLUE_DYE = false
BLUE_DYE = false
PURPLE_DYE = false
MAGENTA_DYE = false
PINK_DYE = false
PAPER = false
BOOK = false
FIREWORK_STAR = false
GLASS_BOTTLE = false
GLOWSTONE_DUST = false
GUNPOWDER = false
DRAGON_BREATH = false
FERMENTED_SPIDER_EYE = false
BLAZE_POWDER = false
SUGAR = false
RABBIT_FOOT = false
GLISTERING_MELON_SLICE = false
MAGMA_CREAM = false
GHAST_TEAR = false
PHANTOM_MEMBRANE = false
EXPERIENCE_BOTTLE = false
END_CRYSTAL = false
ARROW = false
SPECTRAL_ARROW = false
NAME_TAG = false
LEAD = false
RAIL = false
POWERED_RAIL = false
DETECTOR_RAIL = false
ACTIVATOR_RAIL = false
REDSTONE_TORCH = false
REPEATER = false
COMPARATOR = false
LIGHTNING_ROD = false
TORCH = false
SOUL_TORCH = false
LANTERN = false
SOUL_LANTERN = false
CHAIN = false
END_ROD = false
ANVIL = false
CAMPFIRE = false
SOUL_CAMPFIRE = false
ITEM_FRAME = false
GLOW_ITEM_FRAME = false
PAINTING = false
POINTED_DRIPSTONE = false
OAK_SAPLING = false
SPRUCE_SAPLING = false
BIRCH_SAPLING = false
JUNGLE_SAPLING = false
ACACIA_SAPLING = false
DARK_OAK_SAPLING = false
CHERRY_SAPLING = false
MANGROVE_PROPAGULE = false
BROWN_MUSHROOM = false
RED_MUSHROOM = false
CRIMSON_FUNGUS = false
WARPED_FUNGUS = false
DANDELION = false
POPPY = false
BLUE_ORCHID = false
ALLIUM = false
AZURE_BLUET = false
RED_TULIP = false
ORANGE_TULIP = false
WHITE_TULIP = false
PINK_TULIP = false
OXEYE_DAISY = false
CORNFLOWER = false
LILY_OF_THE_VALLEY = false
SUGAR_CANE = false
WITHER_ROSE = false
SUNFLOWER = false
LILAC = false
ROSE_BUSH = false
PEONY = false
TURTLE_EGG = false
WHEAT_SEEDS = false
COCOA_BEANS = false
PUMPKIN_SEEDS = false
MELON_SEEDS = false
BEETROOT_SEEDS = false
SEAGRASS = false
KELP = false
COBWEB = false
WHITE_CARPET = false
LIGHT_GRAY_CARPET = false
GRAY_CARPET = false
BLACK_CARPET = false
BROWN_CARPET = false
RED_CARPET = false
ORANGE_CARPET = false
YELLOW_CARPET = false
LIME_CARPET = false
GREEN_CARPET = false
CYAN_CARPET = false
LIGHT_BLUE_CARPET = false
BLUE_CARPET = false
PURPLE_CARPET = false
MAGENTA_CARPET = false
PINK_CARPET = false
VINE = false
TWISTING_VINES = false
WEEPING_VINES = false
GLOW_LICHEN = false
SCULK_VEIN = false
